### ISSUE TITLE
(formula 4 / 4 * 2)        ->          0.5

### ISSUE THREAD

**Issue by dilvan1** [jbester/cljext#1]
When division appears first in an equation, multiplication is performed first (even when it comes last):

`(formula 4 / 4 * 2)`        ->          1/2          it should be 2.

Also:

* `(formula Math/sin 2)`  ->  works
* `(formula Math/sin (2))`  -> doesn't work ( java.lang.ClassCastException: java.lang.Long cannot be cast to clojure.lang.IFn)
* `(formula Math/sin (* 2 1))`  ->  works

**Comment by jbester** [comment]
The precedence values were incorrect.  Functions were never supported in the infix notation.  Typically functions were bound via a let with formulas for the function parameters.

**Comment by jbester** [comment]
If you don't mind me asking - this repo targets a relatively old version of clojure - what version(s) are you using it on?
